FROM nginx:alpine
#Docker takes our nginx.conf and copys it into its own env (hence the linux paths)
WORKDIR /etc/nginx

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

ENTRYPOINT [ "nginx" ]

CMD [ "-g", "daemon off;" ]